#!/bin/sh

DOTFILES_ENV="$1"
DOTFILES_PLATFORM="$2"

echo "Usage: dotfiles <command> [DOTFILES_ENV=<env>] [DOTFILES_PLATFORM=<platform>]"
echo ""
echo "Commands:"
echo "  init      Set up a new machine:"
echo ""
echo "              - installs platform dependencies (e.g. Homebrew)"
echo "              - creates .env and .config.json from examples"
echo ""
echo "  install   Install all environment packages (e.g. brew bundle)"
echo "  capture   Capture installed packages back into the repository (e.g Brewfile)"
echo ""
echo "  link      Render templates and symlink dotfiles into the machine"
echo "  gather    Gather rendered dotfiles from the machine back into repository templates"
echo ""
echo "  format    Auto-format all .sh and .json files in the repository"
echo "  verify    Run shellcheck and format checks on all scripts and JSON files in the repository"
echo "  env       Print current DOTFILES_ENV and DOTFILES_PLATFORM values"
echo "  where     Print the absolute repository path"
echo "  help      Show this help message"
echo ""
echo "Current: DOTFILES_ENV=$DOTFILES_ENV, DOTFILES_PLATFORM=$DOTFILES_PLATFORM"
echo "Example:  dotfiles link DOTFILES_ENV=homelab DOTFILES_PLATFORM=mac"
