#!/bin/sh

DOTFILES_PROFILE="$1"
DOTFILES_PLATFORM="$2"

echo "Usage: dotfiles <command> [DOTFILES_PROFILE=<env>] [DOTFILES_PLATFORM=<platform>]"
echo ""
echo "Commands:"
echo "  init      Set up a new machine:"
echo ""
echo "              - installs platform dependencies (e.g. Homebrew)"
echo "              - creates .config.json from example"
echo ""
echo "  install   Install all profile packages (e.g. brew bundle)"
echo "  capture   Capture installed packages back into the repository (e.g Brewfile)"
echo ""
echo "  link      Render templates and symlink dotfiles into the machine"
echo "  gather    Gather rendered dotfiles from the machine back into repository templates"
echo "  unlock    Unlock Bitwarden vault for bw:// secret resolution"
echo ""
echo "  format    Auto-format all .sh and .json files in the repository"
echo "  verify    Run shellcheck and format checks on all scripts and JSON files in the repository"
echo "  test      Run end-to-end tests for link and gather against the active profile's test fixtures"
echo "  env       Print current DOTFILES_PROFILE and DOTFILES_PLATFORM values"
echo "  where     Print the absolute repository path"
echo "  help      Show this help message"
echo ""
echo "Current: DOTFILES_PROFILE=$DOTFILES_PROFILE, DOTFILES_PLATFORM=$DOTFILES_PLATFORM"
echo "Example:  dotfiles link DOTFILES_PROFILE=homelab DOTFILES_PLATFORM=mac"
