{
 "title": "qBittorrent",
 "tags": [
  "downloads",
  "qbittorrent"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(qbittorrent_up,server)"
    }
   },
   {
    "name": "categories",
    "label": "Categories",
    "query": {
     "query": "label_values(qbittorrent_torrents_count{server=\"$server\"},category)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Qbittorrent Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "qbittorrent_up{server=\"$server\"}"
    }
   ]
  },
  {
   "title": "Bittorrent network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_connected{server=\"$server\"} - qbittorrent_firewalled{server=\"$server\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "DHT nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "qbittorrent_dht_nodes{server=\"$server\"}",
     "legendFormat": "DHT nodes"
    }
   ]
  },
  {
   "title": "Data uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_up_info_data_total{server=\"$server\"})",
     "legendFormat": "In session "
    },
    {
     "expr": "sum by (app) (qbittorrent_alltime_ul_total{server=\"$server\"})",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Data downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (app) (qbittorrent_dl_info_data_total{server=\"$server\"})",
     "legendFormat": " In session"
    },
    {
     "expr": "sum by (app) (qbittorrent_alltime_dl_total{server=\"$server\"})",
     "legendFormat": "All time"
    }
   ]
  },
  {
   "title": "Accumulated ratio in session",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum by (app) (qbittorrent_alltime_ul_total{server=\"$server\"})) / (sum by (app) (qbittorrent_alltime_dl_total{server=\"$server\"}))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Download speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total{server=\"$server\"}[2m])"
    }
   ]
  },
  {
   "title": "Upload speed",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(qbittorrent_up_info_data_total{server=\"$server\"}[2m])"
    }
   ]
  },
  {
   "title": "Transfer Rates",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(qbittorrent_dl_info_data_total{server=\"$server\"}[2m])",
     "legendFormat": "Download $server"
    },
    {
     "expr": "rate(qbittorrent_up_info_data_total{server=\"$server\"}[2m])",
     "legendFormat": "Upload $server"
    }
   ]
  },
  {
   "title": "Torrents by status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\", status!=\"complete\", server=\"$server\"}) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Torrents by categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(qbittorrent_torrents_count{category=~\"${categories}\",status!=\"complete\",server=\"$server\"}) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  }
 ]
}