{
 "title": "Seerr",
 "tags": [
  "media",
  "seerr"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(jellyseerr_requests_count)", "legendFormat": "Requests" }
   ]
  },
  {
   "title": "Requests by user",
   "type": "piechart",
   "gridPos": { "h": 21, "w": 14, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(jellyseerr_user_requests) > 0",
     "legendFormat": "{{ email }}"
    }
   ]
  },
  {
   "title": "Approved requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{request_status=\"Approved\"})",
     "legendFormat": "Approved "
    }
   ]
  },
  {
   "title": "Pending requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{request_status=\"Pending\"})",
     "legendFormat": "Approved "
    }
   ]
  },
  {
   "title": "Declined requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{request_status=\"Declined\"})",
     "legendFormat": "Approved "
    }
   ]
  },
  {
   "title": "Available requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{media_status=\"Available\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Processing requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{media_status=\"Processing\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Part-available requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyseerr_requests_count{media_status=\"Part-Available\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Requests by media type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jellyseerr_requests_count) by (media_type))",
     "legendFormat": "{{ media_type }}"
    }
   ]
  },
  {
   "title": "Media type count",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum(jellyseerr_requests_count) by (is_4k))",
     "legendFormat": "{{ media_type }}"
    }
   ]
  }
 ]
}